name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_DISTRIBUTION: temurin
  JAVA_PACKAGE: jdk
  JAVA_VERSION: '17'
  MAVEN_CACHE: maven
  MAVEN_OUTPUT: target

jobs:
  compile:
    runs-on: ubuntu-latest
    name: compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Cache maven dependencies
        id: cache-maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          java-version: ${{ env.JAVA_VERSION }}
          #cache: ${{ env.MAVEN_CACHE }}

      - name: mvn compile
        run: ./mvnw -f pom.xml -B compile

      - name: Upload ${{ env.MAVEN_OUTPUT }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MAVEN_OUTPUT }}
          path: ${{ env.MAVEN_OUTPUT }}
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: compile
    name: Run tests with JaCoCo
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Cache maven dependencies
        id: cache-maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Download ${{ env.MAVEN_OUTPUT }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MAVEN_OUTPUT }}

      - name: mvn test-compile
        run: ./mvnw -f pom.xml -B test-compile

      - name: mvn test with JaCoCo
        run: ./mvnw -f pom.xml -B org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: ${{ env.MAVEN_OUTPUT }}/site/jacoco
          retention-days: 7

  analyse:
    runs-on: ubuntu-latest
    needs: compile
    name: SpotBugs and SBOM
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Cache maven dependencies
        id: cache-maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Download ${{ env.MAVEN_OUTPUT }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MAVEN_OUTPUT }}

      - name: mvn spotbugs
        run: ./mvnw com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v4
        with:
          name: SpotBugs
          path: ${{ env.MAVEN_OUTPUT }}/spotbugsXml.xml
          retention-days: 1

      - name: mvn cyclonedx software bill of material (SBOM)
        run: ./mvnw org.cyclonedx:cyclonedx-maven-plugin:makeBom

      - name: Upload SBOM Report
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: |
            ${{ env.MAVEN_OUTPUT }}/bom.json
            ${{ env.MAVEN_OUTPUT }}/bom.xml
          retention-days: 1

  package:
    runs-on: ubuntu-latest
    needs: compile
    name: Build the Maven Project
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Cache maven dependencies
        id: cache-maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Download ${{ env.MAVEN_OUTPUT }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MAVEN_OUTPUT }}

      - name: mvn package without tests
        run: ./mvnw -f pom.xml -B package -DskipTests
