name: OWASP Dependency Check

on:
  push:
    branches:
      - main
      - 'release/**'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  JAVA_DISTRIBUTION: temurin
  JAVA_PACKAGE: jdk
  JAVA_VERSION: '17'
  MAVEN_OUTPUT: target

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: dependency-check
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Cache maven dependencies
        id: cache-maven
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: "${{ runner.os }}-maven-owasp-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-owasp-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-owasp-
            ${{ runner.os }}-maven-

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-package: ${{ env.JAVA_PACKAGE }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: mvn package and dependency-check
        run: |
          ./mvnw --no-transfer-progress package -DskipTests -DskipITs \
            -DnvdApiKey=${{secrets.NVDAPIKEY}} \
            -Dmax.cvss.score=8 \
            -DfailBuildOnCVSS=8 \
            -Dformats=HTML,SARIF \
            -DsuppressionFile=dependency-check-suppression.xml \
            org.owasp:dependency-check-maven:check

      - name: Upload SARIF file to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.MAVEN_OUTPUT }}/dependency-check-report.sarif
          category: dependency-check

      - name: Upload dependency-check Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{ env.MAVEN_OUTPUT }}/dependency-check-report.html
          retention-days: 1